### ISSUE TITLE
error during instalation

### ISSUE THREAD

**Issue by velocirraptor23** [mqcomplab/NAMI#1]
Hi,

Very nice work. I got an error during instalation

ImportError: cannot import name 'PickleBuffer' from 'pickle'

Do you have any clue how to fix this?

Best wishes,

Cesar

**Comment by Ak-Sure** [comment]
Hey,

Sorry for the delayed response. Could you check with your installation of the pickle module and python version. It should work fine with python > 3.10.
